export const awards = [
  {
    name: '01',
    type: ' Web Design',
    project: 'Animation ( 01 )',
    label: 'View',
    year: 'OSX DOCK INTERACTION',
    link: './about.html',
  },
  {
    name: '02',
    type: ' Web Design',
    project: 'Animation ( 02 )',
    label: 'View',
    year: 'STARK SPLIT LOGIC',
    link: './about.html',
  },
  {
    name: '03',
    type: ' Web Design',
    project: 'Animation ( 03 )',
    label: 'View',
    year: 'NAV ITERATION 01',
    link: './about.html',
  },
  {
    name: '04',
    type: ' Web Design',
    project: 'Animation ( 04 )',
    label: 'View',
    year: 'MENU ITERATION 02',
    link: './about.html',
  },
  {
    name: '05',
    type: ' Web Design',
    project: 'Interaction ( 05 )',
    label: 'View',
    year: 'HOLOGRAPHIC DISTORTION',
    link: './about.html',
  },
  {
    name: '06',
    type: ' Web Design',
    project: 'Interaction ( 06 )',
    label: 'View',
    year: 'PROXIMITY SWELL',
    link: './about.html',
  },
  {
    name: '07',
    type: ' Web Design',
    project: 'Animation ( 07 )',
    label: 'View',
    year: 'SHARP SLIDE V1',
    link: './about.html',
  },
  {
    name: '08',
    type: ' Web Design',
    project: 'Animation ( 08 )',
    label: 'View',
    year: 'SCROLL REVEAL SYSTEM',
    link: './about.html',
  },
  {
    name: '09',
    type: ' Web Design',
    project: 'Animation ( 09 )',
    label: 'View',
    year: 'ANGULAR TOPOGRAPHY',
    link: './about.html',
  },
  {
    name: '10',
    type: ' Web Design',
    project: 'Interaction ( 10 )',
    label: 'View',
    year: 'CHAOTIC TYPOGRAPHY',
    link: './about.html',
  },
  {
    name: '11',
    type: ' Web Design',
    project: 'Animation ( 11 )',
    label: 'View',
    year: 'PIXELATED MENU',
    link: './about.html',
  },
  {
    name: '12',
    type: ' Web Design',
    project: 'Animation ( 12 )',
    label: 'View',
    year: 'VELOCITY SCROLL',
    link: './about.html',
  },
  {
    name: '13',
    type: ' Web Design',
    project: 'Animation ( 13 )',
    label: 'View',
    year: 'SEAMLESS TRANSITION',
    link: './about.html',
  },
  {
    name: '14',
    type: ' Web Design',
    project: 'Interaction ( 14 )',
    label: 'View',
    year: 'CARD STACK SEQUENCE',
    link: './about.html',
  },
  {
    name: '15',
    type: ' Web Design',
    project: 'Animation ( 15 )',
    label: 'View',
    year: 'DYNAMIC CLIP 02',
    link: './about.html',
  },
  {
    name: '16',
    type: ' Web Design',
    project: 'Animation ( 16 )',
    label: 'View',
    year: 'DEPTH PARALLAX',
    link: './about.html',
  },
  {
    name: '17',
    type: ' Web Design',
    project: 'Interaction ( 17 )',
    label: 'View',
    year: 'INTERACTIVE DRAG PARALLAX',
    link: './about.html',
  },
  {
    name: '18',
    type: ' Web Design',
    project: 'Animation ( 18 )',
    label: 'View',
    year: 'FLUID PARALLAX',
    link: './about.html',
  },
  {
    name: '19',
    type: ' Web Design',
    project: 'Interaction ( 19 )',
    label: 'View',
    year: 'HIDDEN GLYPH',
    link: './about.html',
  },
  {
    name: '20',
    type: ' Web Design',
    project: 'Interaction ( 20 )',
    label: 'View',
    year: 'BRUTALIST PARALLAX',
    link: './about.html',
  },
];